[main]
analytics_opt_out = off
assetdir = anthias_assets
database = .anthias/anthias.db
date_format = mm/dd/yyyy
splash_logo_url = /static/img/logo-full-splash.svg
use_24_hour_clock = off
use_ssl = off
auth_backend = 
django_secret_key = 

[viewer]
audio_output = hdmi
debug_logging = off
default_duration = 10
default_streaming_duration = 300
player_name = 
resolution = 1920x1080
show_splash = on
shuffle_playlist = off
verify_ssl = on
default_assets = off

[auth_basic]
user = 
password = 

